# Домашняя работа к лекции «Библиотека numpy. Вычислительные задачи»


## Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [61]:
x = np.arange(10)[::-1]
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [91]:
y = np.arange(25)[::-1]
m = y.reshape(5, 5)
print('Сумма значений диагонали (', np.diagonal(m), ') матрицы "m" равна: ', np.trace(m))

Сумма значений диагонали ( [24 18 12  6  0] ) матрицы "m" равна:  60


In [74]:
y

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

In [75]:
m

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

## Задание 3

Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [2]:
from numpy import linalg

In [ ]:
4x + 2y + z = 4 
x + 3y = 12 
5y + 4z = -3

In [87]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ])
b = np.array( [4, 12, -3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [84]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [85]:
4*0.46666667 + 2*3.84444444 - 5.55555556

4.0

## Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [13]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [14]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [15]:
def max_cosine():
    cosine_list = []
    i=0
    for i in users_stats:
        len_next_user_stats = np.linalg.norm( next_user_stats )
        cosine_list.append(np.dot( next_user_stats, i ) / ( len_next_user_stats * np.linalg.norm( i ) ))
        i += 1
    
    print ('Самый подходящий пользователь для "next_user": ID#', cosine_list.index(max(cosine_list))+1,', '\
           'с косинусной метрикой', max(cosine_list))
max_cosine()

Самый подходящий пользователь для "next_user": ID# 8 , с косинусной метрикой 0.9486832980505138
