In [1]:
import pandas as pd
import numpy as np

In [44]:
hr = pd.read_csv('HR.csv')

#формально(чтобы названия всех столбцов начинались с нижнего регистра):
hr.rename(columns = {hr.columns[5]: 'work_accident'}, inplace = True)
hr

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales  medium  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14994                      0    support     low  
14995                      0    support     low  
14996                      0    support     low  
14997                      0    support     low  
14998                      0    support     low  

[14999 rows x 10 columns]

In [45]:
# Определяем признаки (факторы)
df = hr[['satisfaction_level', 'last_evaluation','number_project', 'average_montly_hours', 'time_spend_company', \
         'work_accident', 'promotion_last_5years']]
res = hr.left

In [46]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  work_accident  \
0                       157                   3              0   
1                       262                   6              0   
2                       272                   4              0   
3                       223                   5              0   
4                       159                   3              0   
...                     ...                 ...            ...   
14994                   151                   3              0   
14995                   160                   3              0   
14996                   143                   3              0   
14997                   280                   4              0   
14998                   158                   3              0   

       promotion_last_5years  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0  
...                      ...  
14994                      0  
14995                      0  
14996                      0  
14997                      0  
14998                      0  

[14999 rows x 7 columns]

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   work_accident          14999 non-null  int64  
 6   promotion_last_5years  14999 non-null  int64  
dtypes: float64(2), int64(5)
memory usage: 820.4 KB


In [48]:
res.unique()

array([1, 0], dtype=int64)

In [49]:
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis # импортируем LDA-функционал

In [50]:
X_train, X_test, y_train, y_test = train_test_split(df, res, test_size=0.25) # разделяем выборку на тренировочную и тестовую

In [51]:
lda = LinearDiscriminantAnalysis() # инициализируем LDA-функционал

In [52]:
lda.fit(X_train, y_train) # обучаем данные

LinearDiscriminantAnalysis()

In [53]:
lda.predict(X_test) # делаем прогноз на тестовой выборке

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [54]:
result = pd.DataFrame([y_test, lda.predict(X_test)]).T # смотрим разницу факта и прогноза
result

left  Unnamed 0
10455   0.0        NaN
8240    0.0        NaN
12159   1.0        NaN
424     1.0        0.0
6307    0.0        NaN
...     ...        ...
7716    0.0        NaN
5871    0.0        NaN
11966   0.0        NaN
1790    1.0        0.0
14881   1.0        NaN

[3750 rows x 2 columns]

In [55]:
result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3750 entries, 10455 to 14881
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   left       3750 non-null   float64
 1   Unnamed 0  936 non-null    float64
dtypes: float64(2)
memory usage: 247.9 KB


In [56]:
from sklearn.metrics import accuracy_score

In [57]:
accuracy_score(y_test, lda.predict(X_test))

0.7624

# Без категориальных признаков

In [61]:
df2 = hr[['satisfaction_level', 'last_evaluation','number_project', 'average_montly_hours', 'time_spend_company']]
res = hr.left

In [62]:
df2

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  
0                       157                   3  
1                       262                   6  
2                       272                   4  
3                       223                   5  
4                       159                   3  
...                     ...                 ...  
14994                   151                   3  
14995                   160                   3  
14996                   143                   3  
14997                   280                   4  
14998                   158                   3  

[14999 rows x 5 columns]

In [63]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   satisfaction_level    14999 non-null  float64
 1   last_evaluation       14999 non-null  float64
 2   number_project        14999 non-null  int64  
 3   average_montly_hours  14999 non-null  int64  
 4   time_spend_company    14999 non-null  int64  
dtypes: float64(2), int64(3)
memory usage: 586.0 KB


In [64]:
X_train, X_test, y_train, y_test = train_test_split(df2, res, test_size=0.25) # разделяем выборку на тренировочную и тестовую

In [65]:
lda = LinearDiscriminantAnalysis() # инициализируем LDA-функционал

In [66]:
lda.fit(X_train, y_train) # обучаем данные

LinearDiscriminantAnalysis()

In [67]:
lda.predict(X_test) # делаем прогноз на тестовой выборке

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [68]:
result = pd.DataFrame([y_test, lda.predict(X_test)]).T # смотрим разницу факта и прогноза
result

left  Unnamed 0
14261   1.0        NaN
8677    0.0        NaN
10967   0.0        NaN
977     1.0        0.0
7867    0.0        NaN
...     ...        ...
5676    0.0        NaN
3753    0.0        NaN
5381    0.0        NaN
6976    0.0        NaN
12164   1.0        NaN

[3750 rows x 2 columns]

In [69]:
accuracy_score(y_test, lda.predict(X_test))

0.7509333333333333

In [70]:
# коэффициенты дискриминатных линий
lda.coef_

array([[-4.56501174e+00,  6.86914365e-01, -2.32155769e-01,
         4.18838078e-03,  2.22538761e-01]])

In [ ]:
cmap = colors.LinearSegmentedColormap(
    'red_blue_classes',
    {'red': [(0, 1, 1), (1, 0.7, 0.7)],
     'green': [(0, 0.7, 0.7), (1, 0.7, 0.7)],
     'blue': [(0, 0.7, 0.7), (1, 1, 1)]})
plt.cm.register_cmap(cmap=cmap)

In [ ]:
print(hr.groupby('salary').department.count()[1], 'сотрудников с зарплатой категории:', \
      hr.groupby('salary').department.count().index[1])
print(hr.groupby('salary').department.count()[2], 'сотрудников с зарплатой категории:', \
      hr.groupby('salary').department.count().index[2])
print(hr.groupby('salary').department.count()[0], 'сотрудников с зарплатой категории:', \
      hr.groupby('salary').department.count().index[0])

In [ ]:
print('В отделе', hr['department'].value_counts().index[0], 'работают:', hr['department'].value_counts()[0], 'сотрудников')
print('В отделе', hr['department'].value_counts().index[1], 'работают:', hr['department'].value_counts()[1], 'сотрудников')
print('В отделе', hr['department'].value_counts().index[2], 'работают:', hr['department'].value_counts()[2], 'сотрудников')
print('В отделе', hr['department'].value_counts().index[3], 'работают:', hr['department'].value_counts()[3], 'сотрудников')
print('В отделе', hr['department'].value_counts().index[4], 'работают:', hr['department'].value_counts()[4], 'сотрудников')
print('В отделе', hr['department'].value_counts().index[5], 'работают:', hr['department'].value_counts()[5], 'сотрудников')
print('В отделе', hr['department'].value_counts().index[6], 'работают:', hr['department'].value_counts()[6], 'сотрудников')
print('В отделе', hr['department'].value_counts().index[7], 'работают:', hr['department'].value_counts()[7], 'сотрудников')
print('В отделе', hr['department'].value_counts().index[8], 'работают:', hr['department'].value_counts()[8], 'сотрудников')
print('В отделе', hr['department'].value_counts().index[9], 'работают:', hr['department'].value_counts()[9], 'сотрудников')

In [ ]:
print('Уровень удовлетворенности работой:', hr['satisfaction_level'].mode()[0])
print('Время с момента последней оценки, в годах:', hr['last_evaluation'].mode()[0])
print('Количество проектов, выполненных за время работы:', hr['number_project'].mode()[0])
print('Среднее количество часов на рабочем месте в месяц:', hr['average_montly_hours'].mode()[0])
print('Стаж работы в компании в годах:', hr['time_spend_company'].mode()[0])
print('Происходили ли несчастные случаи на рабочем месте с сотрудником:', hr['work_accident'].mode()[0])
print('Уволился ли сотрудник:', hr['left'].mode()[0])
print('Повышался ли сотрудник за последние пять лет:', hr['promotion_last_5years'].mode()[0])

In [ ]:
print('Уровень удовлетворенности работой:', round(hr['satisfaction_level'].var(), 5))
print('Время с момента последней оценки, в годах:', round(hr['last_evaluation'].var(), 5))
print('Количество проектов, выполненных за время работы:', round(hr['number_project'].var(), 5))
print('Среднее количество часов на рабочем месте в месяц:', round(hr['average_montly_hours'].var(), 5))
print('Стаж работы в компании в годах:', round(hr['time_spend_company'].var(), 5))
print('Происходили ли несчастные случаи на рабочем месте с сотрудником:', round(hr['work_accident'].var(), 5))
print('Уволился ли сотрудник:', round(hr['left'].var(), 5))
print('Повышался ли сотрудник за последние пять лет:', round(hr['promotion_last_5years'].var(), 5))

##### Можно посчитть, в отдельном df, статистические метрики для признаков с Dtype - object (это колонки 'department' и 'salary'). Для этого присвоим им категории. 

In [ ]:
df = hr[['satisfaction_level', 'last_evaluation','number_project', 'average_montly_hours', 'time_spend_company', \
         'work_accident', 'left', 'promotion_last_5years', 'department', 'salary' ]]

df.loc[df.department == 'sales', 'department_cat'] = 1
df.loc[df.department == 'accounting', 'department_cat'] = 2
df.loc[df.department == 'hr', 'department_cat'] = 3
df.loc[df.department == 'technical', 'department_cat'] = 4
df.loc[df.department == 'support', 'department_cat'] = 5
df.loc[df.department == 'IT', 'department_cat'] = 7
df.loc[df.department == 'product_mng', 'department_cat'] = 8
df.loc[df.department == 'marketing', 'department_cat'] = 9
df.loc[df.department == 'RandD', 'department_cat'] = 10
df.loc[df.salary == 'low', 'salary_cat'] = 1
df.loc[df.salary == 'medium', 'salary_cat'] = 2
df.loc[df.salary == 'high', 'salary_cat'] = 3
df['salary_cat'] = df.salary_cat.astype('Int64')
df['department_cat'] = df.department_cat.astype('Int64')
df.head(10)

In [ ]:
print('Среднее арифметическое значение department_cat: ', round(df['department_cat'].mean(), 3))
print('Среднее арифметическое значение salary_cat: ', round(df['salary_cat'].mean(), 3))
print('Значение медианы department_cat: ', df['department_cat'].median())
print('Значение медианы salary_cat: ', df['salary_cat'].median())
print('Значение моды department_cat: ', df['department_cat'].mode()[0])
print('Значение моды salary_cat: ', df['salary_cat'].mode()[0])
print('Минимальное значение department_cat: ', df['department_cat'].min())
print('Минимальное значение salary_cat: ', df['salary_cat'].min())
print('Максимальное значение department_cat: ', df['department_cat'].max())
print('Максимальное значение salary_cat: ', df['salary_cat'].max())
print('Среднее отклонение department_cat: ', round(df['department_cat'].std(), 5))
print('Среднее отклонение salary_cat: ', round(df['salary_cat'].std(), 5))
print('Дисперсия department_cat: ', round(df['department_cat'].var(), 5))
print('Дисперсия salary_cat: ', round(df['salary_cat'].var(), 5))